import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const STYLES = [
  { name: 'Jazz', slug: 'jazz', description: 'Warm, expressive, improvisational. Complex harmony with a groove.', tags: ['instrumental', 'warm', 'complex'] },
  { name: 'Classical', slug: 'classical', description: 'Timeless orchestral and chamber music with depth and structure.', tags: ['orchestral', 'complex', 'acoustic'] },
  { name: 'Lo-fi', slug: 'lofi', description: 'Hazy beats, vinyl warmth, and laid-back energy for focus.', tags: ['chill', 'instrumental', 'calm'] },
  { name: 'House', slug: 'house', description: '4/4 groove, soulful vocals, uplifting energy.', tags: ['electronic', 'dance', 'energetic'] },
  { name: 'Techno', slug: 'techno', description: 'Minimal, industrial, hypnotic rhythms.', tags: ['electronic', 'dark', 'minimal'] },
  { name: 'Ambient', slug: 'ambient', description: 'Atmospheric textures for focus, sleep, and calm.', tags: ['calm', 'instrumental', 'minimal'] },
  { name: 'Cinematic', slug: 'cinematic', description: 'Sweeping orchestral soundscapes that tell a story.', tags: ['orchestral', 'epic', 'instrumental'] },
  { name: 'Funk', slug: 'funk', description: 'Groove-heavy rhythms, punchy bass, and slap guitar.', tags: ['groovy', 'energetic', 'dance'] },
  { name: 'Soul', slug: 'soul', description: 'Emotional vocals, rich harmonies, and warm instrumentation.', tags: ['warm', 'vocal', 'emotional'] },
  { name: 'Hip-Hop', slug: 'hiphop', description: 'Boom-bap, trap, or melodic — hip-hop in all its forms.', tags: ['vocal', 'rhythmic', 'urban'] },
  { name: 'Electronic', slug: 'electronic', description: 'Synthesizers, samples, and digital production.', tags: ['electronic', 'modern'] },
  { name: 'Acoustic', slug: 'acoustic', description: 'Raw, organic sound. Guitar, voice, and space.', tags: ['acoustic', 'warm', 'intimate'] },
  { name: 'Orchestral', slug: 'orchestral', description: 'Full orchestra with rich dynamics and layered arrangements.', tags: ['orchestral', 'complex', 'epic'] },
  { name: 'Piano', slug: 'piano', description: 'Piano as the centrepiece — solo, jazz, or modern.', tags: ['piano', 'acoustic', 'expressive'] },
  { name: 'Latin', slug: 'latin', description: 'Salsa, bossa nova, cumbia, and tropical rhythms.', tags: ['groovy', 'dance', 'warm'] },
  { name: 'Synthwave', slug: 'synthwave', description: '80s-inspired synths, neon vibes, retro-futuristic energy.', tags: ['electronic', 'retro', 'night'] },
  { name: 'Experimental', slug: 'experimental', description: 'Boundary-pushing sounds that defy genre.', tags: ['abstract', 'complex', 'unique'] },
  { name: 'Study', slug: 'study', description: 'Steady focus music for deep concentration.', tags: ['focus', 'calm', 'instrumental'] },
  { name: 'Workout', slug: 'workout', description: 'High-energy beats to push through any session.', tags: ['energetic', 'intense', 'fast'] },
  { name: 'Sleep', slug: 'sleep', description: 'Gentle, slow music for rest and relaxation.', tags: ['calm', 'minimal', 'peaceful'] },
  { name: 'Focus', slug: 'focus', description: 'Non-distracting background music for deep work.', tags: ['focus', 'instrumental', 'minimal'] },
]

const SEED_TRACKS = [
  {
    title: 'Midnight Blue',
    artistName: 'Blue Meridian',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    previewUrl: null,
    artworkUrl: null,
    durationSeconds: 180,
    primaryGenre: 'jazz',
    subgenresJson: JSON.stringify(['cool jazz', 'modern jazz']),
    moodsJson: JSON.stringify(['calm', 'warm', 'night']),
    attributesJson: JSON.stringify({
      bpm: 88,
      energy: 0.38,
      tempo: 'medium-slow',
      instruments: ['upright bass', 'brush drums', 'soft piano', 'muted trumpet'],
      vocals: false,
      danceability: 0.3,
      complexity: 0.6,
      brightness: 0.45,
      acousticBalance: 0.75,
      loopable: false,
      activitySuitability: ['focus', 'study', 'reading'],
    }),
    qualityScore: 0.82,
  },
  {
    title: 'Warm Static',
    artistName: 'Lowrey',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    previewUrl: null,
    artworkUrl: null,
    durationSeconds: 195,
    primaryGenre: 'lofi',
    subgenresJson: JSON.stringify(['chillhop', 'lo-fi hip hop']),
    moodsJson: JSON.stringify(['calm', 'warm', 'dreamy']),
    attributesJson: JSON.stringify({
      bpm: 78,
      energy: 0.28,
      tempo: 'slow',
      instruments: ['sampled piano', 'lo-fi drums', 'vinyl crackle', 'bass guitar'],
      vocals: false,
      danceability: 0.25,
      complexity: 0.35,
      brightness: 0.4,
      acousticBalance: 0.5,
      loopable: true,
      activitySuitability: ['study', 'focus', 'reading', 'cooking'],
    }),
    qualityScore: 0.79,
  },
  {
    title: 'Coastal Drive',
    artistName: 'Verso',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    previewUrl: null,
    artworkUrl: null,
    durationSeconds: 210,
    primaryGenre: 'ambient',
    subgenresJson: JSON.stringify(['atmospheric', 'drone ambient']),
    moodsJson: JSON.stringify(['peaceful', 'dreamy', 'calm']),
    attributesJson: JSON.stringify({
      bpm: null,
      energy: 0.18,
      tempo: 'very slow',
      instruments: ['synthesizer pads', 'field recordings', 'soft piano'],
      vocals: false,
      danceability: 0.05,
      complexity: 0.3,
      brightness: 0.55,
      acousticBalance: 0.2,
      loopable: true,
      activitySuitability: ['sleep', 'focus', 'reading', 'deepwork'],
    }),
    qualityScore: 0.76,
  },
  {
    title: 'Iron Fields',
    artistName: 'Grayden',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    previewUrl: null,
    artworkUrl: null,
    durationSeconds: 168,
    primaryGenre: 'cinematic',
    subgenresJson: JSON.stringify(['epic orchestral', 'trailer music']),
    moodsJson: JSON.stringify(['epic', 'intense', 'mysterious']),
    attributesJson: JSON.stringify({
      bpm: 110,
      energy: 0.82,
      tempo: 'medium-fast',
      instruments: ['full orchestra', 'choir', 'percussion', 'brass'],
      vocals: false,
      danceability: 0.2,
      complexity: 0.75,
      brightness: 0.35,
      acousticBalance: 0.65,
      loopable: false,
      activitySuitability: ['workout', 'gaming', 'deepwork'],
    }),
    qualityScore: 0.85,
  },
  {
    title: 'Sunday Groove',
    artistName: 'The Lowdown',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    previewUrl: null,
    artworkUrl: null,
    durationSeconds: 222,
    primaryGenre: 'funk',
    subgenresJson: JSON.stringify(['neo-soul funk', 'jazz funk']),
    moodsJson: JSON.stringify(['groovy', 'warm', 'happy']),
    attributesJson: JSON.stringify({
      bpm: 98,
      energy: 0.65,
      tempo: 'medium',
      instruments: ['slap bass', 'funk guitar', 'keys', 'horns', 'drums'],
      vocals: false,
      danceability: 0.78,
      complexity: 0.5,
      brightness: 0.7,
      acousticBalance: 0.55,
      loopable: false,
      activitySuitability: ['cooking', 'party', 'walking'],
    }),
    qualityScore: 0.81,
  },
  {
    title: 'Neon Pulse',
    artistName: 'Synthex',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    previewUrl: null,
    artworkUrl: null,
    durationSeconds: 240,
    primaryGenre: 'synthwave',
    subgenresJson: JSON.stringify(['retrowave', 'darksynth']),
    moodsJson: JSON.stringify(['energetic', 'dark', 'mysterious']),
    attributesJson: JSON.stringify({
      bpm: 120,
      energy: 0.72,
      tempo: 'fast',
      instruments: ['analog synths', 'drum machine', 'bass synth', 'arpeggios'],
      vocals: false,
      danceability: 0.68,
      complexity: 0.45,
      brightness: 0.42,
      acousticBalance: 0.05,
      loopable: false,
      activitySuitability: ['workout', 'gaming', 'driving'],
    }),
    qualityScore: 0.77,
  },
  {
    title: 'Rain On Glass',
    artistName: 'Celeste Moor',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    previewUrl: null,
    artworkUrl: null,
    durationSeconds: 185,
    primaryGenre: 'piano',
    subgenresJson: JSON.stringify(['modern classical', 'neoclassical']),
    moodsJson: JSON.stringify(['melancholic', 'peaceful', 'calm']),
    attributesJson: JSON.stringify({
      bpm: 68,
      energy: 0.22,
      tempo: 'slow',
      instruments: ['grand piano', 'soft strings'],
      vocals: false,
      danceability: 0.08,
      complexity: 0.55,
      brightness: 0.48,
      acousticBalance: 0.88,
      loopable: false,
      activitySuitability: ['study', 'reading', 'sleep', 'focus'],
    }),
    qualityScore: 0.88,
  },
  {
    title: 'Digital Bloom',
    artistName: 'Forest Protocol',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    previewUrl: null,
    artworkUrl: null,
    durationSeconds: 198,
    primaryGenre: 'electronic',
    subgenresJson: JSON.stringify(['idm', 'future beats']),
    moodsJson: JSON.stringify(['dreamy', 'warm', 'minimal']),
    attributesJson: JSON.stringify({
      bpm: 105,
      energy: 0.5,
      tempo: 'medium',
      instruments: ['synthesizer', 'chopped samples', 'glitch percussion'],
      vocals: false,
      danceability: 0.55,
      complexity: 0.62,
      brightness: 0.6,
      acousticBalance: 0.1,
      loopable: false,
      activitySuitability: ['focus', 'walking', 'cooking'],
    }),
    qualityScore: 0.74,
  },
  {
    title: 'Savanna',
    artistName: 'Ikotos',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
    previewUrl: null,
    artworkUrl: null,
    durationSeconds: 216,
    primaryGenre: 'latin',
    subgenresJson: JSON.stringify(['bossa nova', 'afro-latin']),
    moodsJson: JSON.stringify(['warm', 'groovy', 'happy']),
    attributesJson: JSON.stringify({
      bpm: 112,
      energy: 0.58,
      tempo: 'medium-fast',
      instruments: ['nylon guitar', 'percussion', 'bass', 'keys'],
      vocals: false,
      danceability: 0.72,
      complexity: 0.48,
      brightness: 0.75,
      acousticBalance: 0.7,
      loopable: false,
      activitySuitability: ['cooking', 'party', 'walking'],
    }),
    qualityScore: 0.8,
  },
  {
    title: 'Frozen Lake',
    artistName: 'Null & Void',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
    previewUrl: null,
    artworkUrl: null,
    durationSeconds: 320,
    primaryGenre: 'ambient',
    subgenresJson: JSON.stringify(['dark ambient', 'drone']),
    moodsJson: JSON.stringify(['dark', 'mysterious', 'calm']),
    attributesJson: JSON.stringify({
      bpm: null,
      energy: 0.12,
      tempo: 'very slow',
      instruments: ['modular synth', 'field recordings', 'textural drones'],
      vocals: false,
      danceability: 0.02,
      complexity: 0.4,
      brightness: 0.2,
      acousticBalance: 0.15,
      loopable: true,
      activitySuitability: ['sleep', 'focus', 'deepwork'],
    }),
    qualityScore: 0.72,
  },
]

async function main() {
  console.log('Seeding database...')

  // Upsert styles
  for (const style of STYLES) {
    const { tags, ...styleFields } = style
    await prisma.style.upsert({
      where: { slug: style.slug },
      create: {
        ...styleFields,
        tagsJson: JSON.stringify(tags),
        popularityScore: Math.random() * 0.5 + 0.3,
      },
      update: {
        description: style.description,
        tagsJson: JSON.stringify(tags),
      },
    })
  }
  console.log(`Upserted ${STYLES.length} styles`)

  // Seed tracks
  let created = 0
  for (const track of SEED_TRACKS) {
    const existing = await prisma.track.findFirst({ where: { title: track.title, artistName: track.artistName } })
    if (!existing) {
      await prisma.track.create({ data: { ...track, status: 'ready_public', visibility: 'public', moderationStatus: 'approved' } })
      created++
    }
  }
  console.log(`Created ${created} seed tracks`)

  console.log('Seed complete.')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
